// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// i2c_master //
// ---------- //

#define i2c_master_wrap_target 0
#define i2c_master_wrap 29
#define i2c_master_pio_version 0

static const uint16_t i2c_master_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0x7041, //  1: out    y, 1            side 0
    0x7021, //  2: out    x, 1            side 0
    0x1066, //  3: jmp    !y, 6           side 0
    0xf881, //  4: set    pindirs, 1      side 1
    0xf180, //  5: set    pindirs, 0      side 0 [1]
    0x1030, //  6: jmp    !x, 16          side 0
    0x7081, //  7: out    pindirs, 1      side 0
    0xf027, //  8: set    x, 7            side 0
    0xb942, //  9: nop                    side 1 [1]
    0x5801, // 10: in     pins, 1         side 1
    0xb742, // 11: nop                    side 0 [7]
    0x1049, // 12: jmp    x--, 9          side 0
    0x7181, // 13: out    pindirs, 1      side 0 [1]
    0xb942, // 14: nop                    side 1 [1]
    0x1018, // 15: jmp    24              side 0
    0xf027, // 16: set    x, 7            side 0
    0x7181, // 17: out    pindirs, 1      side 0 [1]
    0xb942, // 18: nop                    side 1 [1]
    0xb742, // 19: nop                    side 0 [7]
    0x1051, // 20: jmp    x--, 17         side 0
    0x7181, // 21: out    pindirs, 1      side 0 [1]
    0xb942, // 22: nop                    side 1 [1]
    0xb742, // 23: nop                    side 0 [7]
    0x7041, // 24: out    y, 1            side 0
    0x107d, // 25: jmp    !y, 29          side 0
    0xf181, // 26: set    pindirs, 1      side 0 [1]
    0xb942, // 27: nop                    side 1 [1]
    0xf980, // 28: set    pindirs, 0      side 1 [1]
    0xb742, // 29: nop                    side 0 [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2c_master_program = {
    .instructions = i2c_master_program_instructions,
    .length = 30,
    .origin = -1,
    .pio_version = i2c_master_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2c_master_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_master_wrap_target, offset + i2c_master_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

